import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { AppLayout } from '@/components/layouts/AppLayout'
import { Button } from '@/components/buttons/Button'
import { Marquee } from '@/components/Marquee'
import { FAQPreview } from '@/components/FAQPreview'
import { attributes } from '@/content/LandingPage.md'
import type { NextPageWithLayout } from './_app'
import type { ReactElement } from 'react'

const CourseCard = () => {
  return (
    <div className="h-[462px] min-w-[369px] max-w-[369px] bg-gradient-to-br from-te-lblue to-te-green rounded-2xl flex justify-center items-center drop-shadow-lg">
      <div className="h-[460px] min-w-[367px] max-w-[367px] bg-white rounded-2xl px-6 py-7">
        <div className="rounded-2xl">
          <Image
            height="210"
            layout="responsive"
            src="/assets/course_card_placeholder.png"
            width="320"
          />
        </div>
        <div className="my-6 flex flex-col gap-y-2">
          <span className="text-xl font-bai font-bold">
            Introduction to cryptoeconomic system
          </span>
          <span className="text-sm text-gray-400 font-open font-semibold">
            TE Fundamentals Part 1
          </span>
        </div>
        <div className="mb-6 border-t-[0.4px]" />
        <div className="flex justify-between">
          <div className="w-1/2 flex items-center gap-2">
            <div className="h-[44px] w-[44px] bg-te-purple rounded-full" />
            <span className="text-xs font-open font-semibold">
              TE Academy Akrtws
            </span>
          </div>
          <div className="w-[1px] border-l-[0.4px]" />
          <div className="w-1/2 flex justify-end items-center gap-2">
            <Image height="16" src="/icons/hat.svg" width="16" />
            <span className="text-xs font-open font-semibold">20 enrolled</span>
            <Image height="44" src="/arrow_button.svg" width="44" />
          </div>
        </div>
      </div>
    </div>
  )
}

interface IBadge {
  content: string
  title: string
}

const Badge = ({ content, title }: IBadge) => {
  return (
    <div className="max-w-xs flex flex-col gap-y-5 justify-center items-center">
      <div className="h-[205px] w-[205px] bg-[#FAEFFF] rounded-full flex items-center justify-center">
        <Image height="100" src="/ribbon.svg" width="100" />
      </div>
      <span className="my-auto text-2xl text-center font-bai font-bold">
        {title}
      </span>
      <span className="text-sm text-gray-400 text-center font-open">
        {content}
      </span>
    </div>
  )
}

const partners = [
  { height: '52', src: '/logos/partners/apple.svg', width: '45' },
  { height: '32', src: '/logos/partners/jeep.svg', width: '80' },
  { height: '40', src: '/logos/partners/google_plus.svg', width: '65' },
  { height: '28', src: '/logos/partners/nike.svg', width: '81' },
  { height: '33', src: '/logos/partners/tripadvisor.svg', width: '53' },
  { height: '45', src: '/logos/partners/github.svg', width: '45' }
]

const badges = [
  {
    content:
      'Learn token engineering, at your own pace, wherever you are. Join study groups and learn together. Earn your certificate.',
    title: 'Advance your Knowledge'
  },
  {
    content:
      'Learn token engineering, at your own pace, wherever you are. Join study groups and learn together. Earn your certificate.',
    title: 'Join, Contribute & Network'
  },
  {
    content:
      'Learn token engineering, at your own pace, wherever you are. Join study groups and learn together. Earn your certificate.',
    title: 'Collaborate and start your professional TE career'
  }
]

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>TE Academy</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <div className="w-full bg-[url('/gray_bg.png')]">
        <div className="grid grid-cols-2 pb-28 pt-[230px] px-28">
          <div className="flex flex-col gap-y-9">
            <span className="text-6xl font-bai font-bold">
              {attributes.mainTitle}
            </span>
            <span className="text-gray-400 text-2xl font-bai">
              {attributes.subtitle}
            </span>
            <div className="h-16 w-48">
              <Button label="Get Started" />
            </div>
            <span className="text-xl text-te-purple font-bai font-bold">
              {attributes.partnersTitle}
            </span>
            <div className="flex items-end gap-x-8">
              {partners.map((partner) => (
                <Image
                  key={`${partner.height}x${partner.width}`}
                  height={partner.height}
                  src={partner.src}
                  width={partner.width}
                />
              ))}
            </div>
          </div>
          <div>
            <Image
              height="680"
              layout="responsive"
              src="/assets/landing_page.svg"
              width="815"
            />
          </div>
        </div>
        <div className="bg-te-dark pl-28 py-24">
          <div className="grid grid-cols-2 justify-center items-center pb-24">
            <div className="flex flex-col gap-y-4">
              <span className="text-7xl text-white font-bai font-bold">
                {attributes.coursesTitle}
              </span>
              <span className="text-2xl text-white font-bai">
                {attributes.teFundamentalsSubtitle}
              </span>
            </div>
            <div className="h-16 w-48 mx-auto">
              <Button reverse label="Explore Courses" />
            </div>
          </div>
          <div className="flex gap-x-6 py-6 overflow-scroll">
            <CourseCard />
            <CourseCard />
            <CourseCard />
            <CourseCard />
            <CourseCard />
          </div>
        </div>
        <div className="bg-[#FDF8FF] py-32">
          <div className="flex flex-col gap-y-4 justify-center items-center max-w-2xl mx-auto">
            <span className="text-5xl text-center font-bai font-bold">
              {attributes.learnTitle}
            </span>
            <span className="text-2xl text-center font-bai">
              {attributes.learnSubtitle}
            </span>
          </div>
          <div className="mt-16 flex gap-x-16 justify-center">
            {badges.map((badge) => (
              <Badge
                key={badge.title}
                content={badge.content}
                title={badge.title}
              />
            ))}
          </div>
        </div>
        <div className="bg-white px-28 py-32">
          <div className="flex flex-col gap-y-4 justify-center items-center max-w-2xl mx-auto pb-24">
            <span className="text-5xl text-center font-bai font-bold">
              {attributes.liveCoursesTitle}
            </span>
            <span className="text-2xl text-center font-bai">
              {attributes.liveCoursesSubtitle}
            </span>
          </div>
          <div className="flex gap-x-6 py-6 overflow-scroll">
            <CourseCard />
            <CourseCard />
            <CourseCard />
            <CourseCard />
            <CourseCard />
          </div>
          <div className="h-16 w-48">
            <Button reverse label="See Live Courses" />
          </div>
        </div>
        <Marquee />
        <FAQPreview />
      </div>
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <AppLayout navBarIsTransparent>{page}</AppLayout>
}

export default Home
