backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
publish_mode: editorial_workflow
collections:
  - name: faq
    label: FAQ
    files: content/faq.md
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
      - name: faq
        label: FAQ
        widget: list
        fields:
          - label: Question
            name: question
            widget: string
          - label: Answer
            name: answer
            widget: string
        multiple: true
  - name: terms-conditions
    label: Terms & Conditions
    folder: content/terms-conditions
    create: true
    fields:
      - label: Name
        name: name
        widget: string
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
  - name: privacy-policy
    label: Privacy Policy
    folder: content/privacy-policy
    create: true
    fields:
      - label: Name
        name: name
        widget: string
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
  - name: live-courses
    label: Live Courses
    folder: content/live-courses
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
      - label: Author id
        name: author-id
        widget: string
      - label: Nº of enrolled students
        name: enrolled-students
        widget: number
      - label: Course date
        name: course-date
        widget: date
        default: ""
        format: MMM Do YY
      - label: Course link
        name: course-link
        widget: string
      - label: Course image
        name: course-image
        widget: image
  - name: partners
    label: Partners
    folder: content/partners
    create: true
    fields:
      - label: Name
        name: name
        widget: string
      - label: Description
        name: description
        widget: string
      - label: Image
        name: image
        widget: image
  - name: gallery
    label: Gallery
    folder: content/gallery
    create: true
    fields:
      - label: Image
        name: image
        widget: image
      - label: Description
        name: description
        widget: string
  - name: core-team
    label: Core Team
    folder: content/core-team
    create: true
    fields:
      - label: Name
        name: name
        widget: string
      - label: Role
        name: role
        widget: string
      - label: LinkedIn
        name: linkedin
        widget: string
      - label: Facebook
        name: facebook
        widget: string
      - label: Instagram
        name: instagram
        widget: string
      - label: Image
        name: image
        widget: image
  - name: authors
    label: Authors
    folder: content/authors
    create: true
    fields:
      - label: Name
        name: name
        widget: string
      - label: Description
        name: description
        widget: string
      - label: LinkedIn
        name: linkedin
        widget: string
      - label: Facebook
        name: facebook
        widget: string
      - label: Instagram
        name: instagram
        widget: string
      - label: Image
        name: image
        widget: image
  - name: testimonials
    label: Testimonials
    folder: content/testimonials
    create: true
    fields:
      - label: Testimonial title
        name: testimonial-title
        widget: string
      - label: Testimonial body
        name: testimonial-body
        widget: markdown
      - label: Testimonial name
        name: testimonial-name
        widget: string
      - label: Testimonial role
        name: testimonial-role
        widget: string
      - label: Image
        name: image
        widget: image
  - name: pages
    label: Pages
    files:
      - name: sign-up
        label: Sign Up/In Page
        file: content/sign-up.yml
        fields:
          - label: Main title
            name: main-title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Sign up message title
            name: sign-up-message-title
            widget: string
          - label: Sign up message subtitle
            name: sign-up-message-subtitle
            widget: string
          - label: Sign in message title
            name: sign-in-message-title
            widget: string
          - label: Sign in message subtitle
            name: sign-in-message-subtitle
            widget: string
      - name: landing-page
        label: Landing Page
        file: content/landing-page.yml
        fields:
          - label: Main title
            name: main-title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Landing banner
            name: landing-banner
            widget: image
          - label: Partners title
            name: partners-title
            widget: string
          - label: Courses title
            name: courses-title
            widget: string
          - label: TE Fundamentals subtitle
            name: te-fundamentals-subtitle
            widget: string
          - label: Learn title
            name: learn-title
            widget: string
          - label: Learn subtitle
            name: learn-subtitle
            widget: string
          - label: Learn icon left title
            name: learn-left-title
            widget: string
          - label: Learn icon left subtitle
            name: learn-left-subtitle
            widget: string
          - label: Learn icon center title
            name: learn-center-title
            widget: string
          - label: Learn icon center subtitle
            name: learn-center-subtitle
            widget: string
          - label: Learn icon right title
            name: learn-right-title
            widget: string
          - label: Learn icon right subtitle
            name: learn-right-subtitle
            widget: string
          - label: Live courses title
            name: live-courses-title
            widget: string
          - label: Live courses subtitle
            name: live-courses-subtitle
            widget: string
      - name: courses-page
        label: Courses Page
        file: content/courses-page.yml
        fields:
          - label: Main title
            name: main-title
            widget: string
          - label: Courses title
            name: courses-title
            widget: string
      - name: contact-page
        label: Contact Page
        file: content/contact-page.yml
        fields:
          - label: Main title
            name: main-title
            widget: string
          - label: Contact title
            name: contact-title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
      - name: faq-page
        label: FAQ Page
        file: content/faq-page.yml
        fields:
          - label: Main title
            name: main-title
            widget: string
      - name: terms-conditions-page
        label: Terms & Conditions Page
        file: content/terms-conditions-page.yml
        fields:
          - label: Main title
            name: main-title
            widget: string
      - name: privacy-policy-page
        label: Privacy Policy Page
        file: content/privacy-policy-page.yml
        fields:
          - label: Main title
            name: main-title
            widget: string
      - name: study-page
        label: Study Page
        file: content/study-page.yml
        fields:
          - label: Main title
            name: main-title
            widget: string
          - label: Study title
            name: study-title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Body
            name: body
            widget: markdown
          - label: Steps title
            name: steps-title
            widget: string
          - label: Study banner
            name: study-banner
            widget: image
          - label: Study Steps
            name: study-steps
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Body
                name: body
                widget: markdown
            multiple: true
      - name: about-page
        label: About Page
        file: content/about-page.yml
        fields:
          - label: Main title
            name: main-title
            widget: string
          - label: About title
            name: about-title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Body
            name: body
            widget: markdown
          - label: About banner
            name: about-banner
            widget: image
          - label: Core team title
            name: core-team-title
            widget: string
          - label: Current stats title
            name: current-stats-title
            widget: string
          - label: Stats numbers left
            name: stats-numbers-left
            widget: string
          - label: Stats numbers center
            name: stats-numbers-center
            widget: string
          - label: Stats numbers right
            name: stats-numbers-right
            widget: string
          - label: Testimonials title
            name: testimonials-title
            widget: string
          - label: Testimonials subtitle
            name: testimonials-subtitle
            widget: string
          - label: Gallery title
            name: gallery-title
            widget: string
          - label: Gallery subtitle
            name: gallery-subtitle
            widget: string
          - label: Footer title
            name: footer-title
            widget: string
          - label: Footer body
            name: footer-body
            widget: string
          - label: Footer image
            name: footer-image
            widget: image
