backend:
  name: git-gateway
  branch: production
media_folder: public/img
public_folder: img
publish_mode: editorial_workflow
collections:
  - name: assets
    label: Assets
    files:
      - name: liveCourses
        label: Live Courses
        file: src/content/LiveCourses.md
        fields:
          - name: liveCourses
            label: Live Courses
            widget: list
            fields:
              - label: Course ID
                name: courseId
                widget: string
              - label: Title
                name: title
                widget: string
              - label: Subtitle
                name: subtitle
                widget: string
              - label: Vendor
                name: vendor
                widget: string
              - label: Vendor Avatar
                name: vendorAvatar
                widget: image
              - label: Course Category
                name: courseCategory
                widget: select
                options: [Virtual Live Session, IRL Events]
              - label: Description
                name: description
                widget: text
              - label: CTA Text
                name: ctaText
                widget: string
              - label: Registration Form Link
                name: registrationFormLink
                widget: string
              - label: Course Start
                name: courseStart
                widget: datetime
                default: ""
                date_format: DD.MM.YYYY
                time_format: HH:mm
                required: false
              - label: Course End
                name: courseEnd
                widget: datetime
                default: ""
                date_format: DD.MM.YYYY
                time_format: HH:mm
                required: false
              - label: Course Link
                name: courseLink
                widget: string
              - label: Show at Homepage
                name: showHomepage
                widget: boolean
                default: true
              - label: Course image
                name: courseImage
                widget: image
            multiple: true
      - name: eventsCalendar
        label: Events Calendar
        file: src/content/EventsCalendar.md
        fields:
          - name: eventsCalendar
            label: Events Calendar
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Subtitle
                name: subtitle
                widget: string
              - label: Host
                name: host
                widget: string
              - label: Course Category
                name: courseCategory
                widget: select
                options: [Virtual Live Session, IRL Events]
              - label: Event Date
                name: eventDate
                widget: datetime
                default: ""
                date_format: DD.MM.YYYY
                time_format: HH:mm
              - label: Url
                name: url
                widget: string
              - label: Course ID
                name: courseId
                widget: string
              - label: Event image
                name: eventImage
                widget: image
            multiple: true
      - name: partners
        label: Partners
        file: src/content/Partners.md
        fields:
          - name: partners
            label: Partners
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Description
                name: description
                widget: string
              - label: Image
                name: image
                widget: image
            multiple: true
      - name: gallery
        label: Gallery
        file: src/content/Gallery.md
        fields:
          - name: gallery
            label: Gallery
            widget: list
            fields:
              - label: Image
                name: image
                widget: image
              - label: Description
                name: description
                widget: string
            multiple: true
      - name: coreTeam
        label: Core Team
        file: src/content/CoreTeam.md
        fields:
          - name: coreTeam
            label: Core Team
            widget: list
            fields:
              - label: User Id
                name: userId
                widget: string
              - label: Name
                name: name
                widget: string
              - label: Role
                name: role
                widget: string
              - label: Description
                name: description
                widget: string
              - label: Image
                name: image
                widget: image
            multiple: true
  - name: pages
    label: Pages
    files:
      - name: signUp
        label: Sign Up Page
        file: src/content/SignUp.md
        fields:
          - label: Main title
            name: mainTitle
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Message title
            name: messageTitle
            widget: string
          - label: Message subtitle
            name: messageSubtitle
            widget: string
      - name: signIn
        label: Sign In Page
        file: src/content/SignIn.md
        fields:
          - label: Main title
            name: mainTitle
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Message title
            name: messageTitle
            widget: string
          - label: Message subtitle
            name: messageSubtitle
            widget: string
      - name: landingPage
        label: Landing Page
        file: src/content/LandingPage.md
        fields:
          - label: Main title
            name: mainTitle
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Landing banner
            name: landingBanner
            widget: image
          - label: Partners title
            name: partnersTitle
            widget: string
          - label: Courses title
            name: coursesTitle
            widget: string
          - label: Courses subtitle
            name: teFundamentalsSubtitle
            widget: string
          - label: Learn title
            name: learnTitle
            widget: string
          - label: Learn subtitle
            name: learnSubtitle
            widget: string
          - label: Learn Content
            name: learnContent
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Subtitle
                name: subtitle
                widget: string
              - label: Badge icon
                name: badgeIcon
                widget: image
            multiple: true
          - label: Live courses title
            name: liveCoursesTitle
            widget: string
          - label: Live courses subtitle
            name: liveCoursesSubtitle
            widget: string
      - name: courses-page
        label: Courses Page
        file: content/courses-page.md
        fields:
          - label: Main title
            name: main-title
            widget: string
          - label: Courses title
            name: courses-title
            widget: string
      - name: contactPage
        label: Contact Page
        file: src/content/ContactPage.md
        fields:
          - label: Main title
            name: mainTitle
            widget: string
          - label: Contact title
            name: contactTitle
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
      - name: faq
        label: FAQ
        file: src/content/FaqPage.md
        fields:
          - name: mainTitle
            label: Main title
            widget: string
          - name: faqContent
            label: FAQ Section
            widget: list
            fields:
              - name: title
                label: Title
                widget: string
              - name: description
                label: Description
                widget: string
              - name: faqQuestions
                label: FAQ
                widget: list
                fields:
                  - label: Question
                    name: question
                    widget: string
                  - label: Answer
                    name: answer
                    widget: text
                multiple: true
            multiple: true
      - name: termsConditionsPage
        label: Terms & Conditions Page
        file: src/content/TermsConditionsPage.md
        fields:
          - name: mainTitle
            label: Main title
            widget: string
          - name: termsConditionsContent
            label: Terms & Conditions
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Title
                name: title
                widget: string
              - label: Body
                name: body
                widget: text
            multiple: true
      - name: privacyPolicyPage
        label: Privacy Policy Page
        file: src/content/PrivacyPolicyPage.md
        fields:
          - name: mainTitle
            label: Main title
            widget: string
          - name: privacyPolicyContent
            label: Privacy Policy
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Title
                name: title
                widget: string
              - label: Body
                name: body
                widget: text
            multiple: true
      - name: studyPage
        label: Study Page
        file: src/content/StudyPage.md
        fields:
          - label: Main title
            name: mainTitle
            widget: string
          - label: Study title
            name: studyTitle
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: BodyContent
            name: bodyContent
            widget: text
          - label: Steps title
            name: stepsTitle
            widget: string
          - label: Study banner
            name: studyBanner
            widget: image
          - label: Study Steps
            name: studySteps
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Body
                name: body
                widget: text
            multiple: true
      - name: aboutPage
        label: About Page
        file: src/content/AboutPage.md
        fields:
          - label: Main title
            name: mainTitle
            widget: string
          - label: About title
            name: aboutTitle
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Body
            name: body
            widget: text
          - label: About banner
            name: aboutBanner
            widget: image
          - label: Core team title
            name: coreTeamTitle
            widget: string
          - label: Current stats title
            name: currentStatsTitle
            widget: string
          - label: Stats numbers left
            name: statsNumbersLeft
            widget: string
          - label: Stats numbers center
            name: statsNumbersCenter
            widget: string
          - label: Stats numbers right
            name: statsNumbersRight
            widget: string
          - label: Testimonials title
            name: testimonialsTitle
            widget: string
          - label: Testimonials subtitle
            name: testimonialsSubtitle
            widget: string
          - label: Gallery title
            name: galleryTitle
            widget: string
          - label: Gallery subtitle
            name: gallerySubtitle
            widget: string
          - label: Footer title
            name: footerTitle
            widget: string
          - label: Footer body
            name: footer-body
            widget: string
          - label: Footer image
            name: footerImage
            widget: image
          - name: testimonials
            label: Testimonials
            widget: list
            fields:
              - label: Testimonial title
                name: testimonialTitle
                widget: string
              - label: Testimonial body
                name: testimonialBody
                widget: text
              - label: Testimonial name
                name: testimonialName
                widget: string
              - label: Testimonial role
                name: testimonialRole
                widget: string
              - label: Image
                name: image
                widget: image
            multiple: true
